version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_worker
    restart: unless-stopped
    volumes:
      - ./python:/app
    networks:
      - app_network
    depends_on:
      - redis

networks:
  app_network:
    driver: bridge
